[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB
board_build.partitions = huge_app.csv

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    ; Wordt aangevuld zodra WiFi/HTTP bibliotheken toegevoegd worden
